name: toy-robot
version: '0.1.0.0'
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: OtherLicense
github: AlistairB/borg

extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Widentities
- -Wredundant-constraints
- -Wmissing-import-lists
- -Wmonomorphism-restriction

default-extensions:
- MultiWayIf

dependencies:
  - base >= 4.11 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Lib
  - Parser
  - BoardProcessor
  - BoardFunctions
  - Types
  dependencies:
  - megaparsec
  - lens
  - mtl

executables:
  toy-robot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-robot

tests:
  toy-robot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-robot
    - hspec
    - QuickCheck
    - checkers
    - hspec-checkers
    - lens
    - mtl
